// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpWJsMK0XhE3fSM0i0_eNRQcrTrwFNokE',
    appId: '1:126337938635:web:b856f8a3ca0b1c2e22974e',
    messagingSenderId: '126337938635',
    projectId: 'quizmatch-e49d4',
    authDomain: 'quizmatch-e49d4.firebaseapp.com',
    storageBucket: 'quizmatch-e49d4.appspot.com',
    measurementId: 'G-Q6VGG28V99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJcuNUtGRuT7G0aqL_-UoWw0KXHa14mHc',
    appId: '1:126337938635:android:88c4ceba17d520a922974e',
    messagingSenderId: '126337938635',
    projectId: 'quizmatch-e49d4',
    storageBucket: 'quizmatch-e49d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxrrwbUaljRBDLZGqn0Tk_k8yLiv037W0',
    appId: '1:126337938635:ios:a8f6ec244956d7bb22974e',
    messagingSenderId: '126337938635',
    projectId: 'quizmatch-e49d4',
    storageBucket: 'quizmatch-e49d4.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxrrwbUaljRBDLZGqn0Tk_k8yLiv037W0',
    appId: '1:126337938635:ios:a8f6ec244956d7bb22974e',
    messagingSenderId: '126337938635',
    projectId: 'quizmatch-e49d4',
    storageBucket: 'quizmatch-e49d4.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpWJsMK0XhE3fSM0i0_eNRQcrTrwFNokE',
    appId: '1:126337938635:web:5c4924ec97737a0122974e',
    messagingSenderId: '126337938635',
    projectId: 'quizmatch-e49d4',
    authDomain: 'quizmatch-e49d4.firebaseapp.com',
    storageBucket: 'quizmatch-e49d4.appspot.com',
    measurementId: 'G-30K8R3N3H0',
  );
}
